<?php
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pacificnm-update for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate($this->layout()->pageTitle); ?> 
				</h3>
				<div class="box-tools"></div>
			</div>
			<div class="box-body box-profile">
				<div class="alert alert-info">
					<p><i class="fa fa-info-circle"></i>
						<?php echo $this->translate("Unable to connect."); ?>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
